[project]
name = 'Decentralized-Transportation-Intermodal-Logistics'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.cost-optimization]
path = 'contracts/cost-optimization.clar'
clarity_version = 2
epoch = 2.5

[contracts.documentation-management]
path = 'contracts/documentation-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
